/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const posts = {
  'whoa-whoa-whoa': {
    id: 0,

    component: /*#__PURE__*/ React.lazy(() => import('./0-whoa-whoa-whoa.mdx')),
    metadata: {
      id: 0,
      timestamp: 1597553433835,
      title: 'Whoa whoa whoa',
      description: 'Hello hello hello',
      tags: [],
      categories: [],
    },
  },

  'hello-world': {
    id: 1,

    component: /*#__PURE__*/ React.lazy(() => import('./1-hello-world.mdx')),
    metadata: {
      id: 1,
      timestamp: 1597553470215,
      title: 'Hello world',
      description: 'This is a blog post.',
      tags: [],
      categories: [],
    },
  },
  'another-post': {
    id: 2,
    component: /*#__PURE__*/ React.lazy(() => import('./2-another-post.mdx')),
    metadata: {
      id: 2,
      timestamp: 1597553898221,
      title: 'Another post',
      description: 'Yet another post',
      tags: [],
      categories: [],
    },
  },
}
