/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const posts = {
  'whoa-whoa-whoa': {
    id: 0,

    component: /*#__PURE__*/ React.lazy(() => import('./0-whoa-whoa-whoa.mdx')),
    metadata: {
      timestamp: 1597553433835,
      title: 'Whoa whoa whoa',
      description: 'Hello hello hello',
      tags: [],
      categories: [],
    },
    testing12: {34: 56},
  },

  'another-post': {
    id: 2,

    component: /*#__PURE__*/ React.lazy(() => import('./2-another-post.mdx')),
    metadata: {
      timestamp: 1597553898221,
      title: 'Another post',
      description: 'Yet another post',
      tags: [],
      categories: [],
    },
  },

  'fix-that-bug': {
    id: 3,

    component: /*#__PURE__*/ React.lazy(() => import('./3-fix-that-bug.mdx')),
    metadata: {
      title: 'Fix that bug',
      description: 'Does it fix the bug?',
      timestamp: 1597556571967,
      tags: [],
      categories: [],
    },
  },
}
