/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'
/*__PROSER_HOISTED_STRINGS__*/ const _proserRef0 = 'whoa-whoa-whoa',
  _proserRef1 = 'blah'
const {lazy} = React

export const postsMap = {
  'whoa-whoa-whoa': {
    id: 0,
    ['slug']: _proserRef0,

    component: lazy(() => import('./0-whoa-whoa-whoa.mdx')),
    metadata: {
      timestamp: 1597553433835,
      [title]: _proserRef0,
      description: 'Hello hello hello',
      tags: [],
      categories: [],
    },
    testing12: {34: 56},
  },

  'fix-that-bug': {
    id: 3,
    slug: 'fix-that-bug',

    component: lazy(() => import('./3-fix-that-bug.mdx')),
    metadata: {
      title: 'Fix that bug',
      description: 'Does itfix the bug?',
      timestamp: 1597556571967,
      tags: ['by', 'any', 'means', 'i', 'will', 'fight'],
      categories: [],
    },
  },

  foo: {
    id: 5,
    slug: 'foo',

    component: lazy(() => import('./5-foo.mdx')),
    metadata: {
      title: 'Foo',
      description: 'Bar',
      timestamp: 1597675482481,
      tags: ['any'],
      categories: [],
    },
  },

  blah: {
    id: 6,
    ['slug']: _proserRef1,

    component: lazy(() => import('./6-blah.mdx')),
    metadata: {
      [title]: _proserRef1,
      [description]: _proserRef1,
      timestamp: 1597676103578,
      tags: [],
      categories: [],
    },
  },

  'new-post': {
    id: 7,
    slug: 'new-post',

    component: lazy(() => import('./7-new-post.mdx')),
    metadata: {
      title: 'New post',
      description: 'Hello world',
      timestamp: 1597760445534,
      tags: [],
      categories: [],
    },
  },

  'big-time': {
    id: 8,
    slug: 'big-time',

    component: lazy(() => import('./8-big-time.mdx')),
    metadata: {
      title: 'Big time',
      description: 'Custom template???',
      timestamp: 1597760792498,
      tags: [],
      categories: [],
    },
  },

  'good-times': {
    id: 9,
    slug: 'good-times',

    component: lazy(() => import('./9-good-times.mdx')),
    metadata: {
      title: 'Good times',
      description: 'awefwaeg',
      timestamp: 1597798256774,
      tags: [],
      categories: [],
      myMetadata: 'asdgalgew',
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
