/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'
/*__PROSER_HOISTED_STRINGS__*/ const _proserRef0 = 'hello-recipes'
const {lazy} = React

export const postsMap = {
  'hello-recipes': {
    id: 0,
    slug: 'hello-recipes',
    component: lazy(() => import('./0-hello-recipes.mdx')),
    metadata: {
      title: 'Hello recipes',
      description: 'maybe this does something',
      timestamp: 1597723042440,
      tags: [],
      categories: [],
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
