/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const postsMap = {
  'ehh-default-template': {
    id: 0,
    slug: 'ehh-default-template',
    component: /*#__PURE__*/ React.lazy(() =>
      import('./0-ehh-default-template.mdx')
    ),
    metadata: {
      title: 'Ehh default template',
      description: 'back in style',
      timestamp: 1597761531208,
      tags: [],
      categories: [],
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
